"""
Conversion Engine.
Monitors leads in ONBOARDING stage and fires targeted nudges when:
  - Lead goes inactive (no message in N hours)
  - Lead is stuck on the same step too long
  - Urgency signals detected (competitor activity, limited windows)
  - Onboarding step regressed or stalled

All nudges are generated by Claude with context-specific urgency framing.
Conversion events (pool created) are timestamped and broadcast to dashboard.
"""
from __future__ import annotations

import asyncio
import logging
import uuid
from datetime import datetime, timedelta, timezone
from typing import Any

from sqlalchemy import select, func

from app.core.config import settings
from app.core.redis import (
    QueueName, ScheduleKey, enqueue, get_redis,
    is_agent_enabled, schedule_task,
)
from app.db.session import AsyncSessionLocal
from app.db.crud import get_lead, log_event, transition_stage
from app.models.lead import EventType, LeadStage, OutreachChannel
from app.services.gemini_client import complete, format_lead_context
from app.services.outreach_composer import OUTREACH_SYSTEM

logger = logging.getLogger(__name__)

# ── Inactivity thresholds ─────────────────────────────────────────────────────
INACTIVITY_NUDGE_HOURS   = 24    # nudge if no reply in 24h
MAX_HOURS_PER_STEP       = 72    # max time on a single onboarding step
STALE_ONBOARDING_DAYS    = 7     # mark concern if no progress in 7 days


# ── Nudge message generator ───────────────────────────────────────────────────

async def generate_nudge(
    lead: dict[str, Any],
    nudge_type: str,
    step_name: str,
    hours_inactive: float,
) -> str:
    """
    Generate a nudge message. Each type takes a different angle:
    - inactivity:  re-engage with a relevant hook
    - stuck_step:  address what might be blocking them
    - urgency:     limited window or competitive signal
    - final_push:  direct "are you still interested?" close
    """
    lead_ctx = format_lead_context(lead)

    type_instructions = {
        "inactivity": f"""The lead went quiet {hours_inactive:.0f} hours ago.
Write a re-engagement message. Hook it to something relevant to their chain or a market signal.
Do NOT say "just checking in" or "following up". Make it feel timely, not chasing.""",

        "stuck_step": f"""The lead has been stuck on the '{step_name}' onboarding step for {hours_inactive:.0f}+ hours.
Something is blocking them. Write a message that:
- Names the specific step they're on (naturally, not robotically)
- Offers to help with whatever is stopping them
- Asks a direct single question to unblock
Max 3 sentences.""",

        "urgency": """Write a message that creates genuine urgency without being fake.
Use one of: limited campaign slot availability, other projects in their chain launching on AimHigher,
or current market conditions being favourable for a campaign launch.
Be specific — vague urgency gets ignored. Max 2 sentences.""",

        "final_push": """This lead has been in onboarding a long time. Write a direct, respectful close.
Acknowledge it's been a while, offer to pause and come back if timing isn't right,
but make it clear the door closes soon. 2 sentences max. Confident, not desperate.""",
    }

    instruction = type_instructions.get(nudge_type, type_instructions["inactivity"])

    user_prompt = f"""Write a nudge message.

Lead: {lead_ctx}
Nudge type: {nudge_type}

{instruction}"""

    msg = await complete(
        system=OUTREACH_SYSTEM,
        messages=[{"role": "user", "content": user_prompt}],
        max_tokens=200,
        temperature=0.85,
    )
    return msg.strip()


# ── Conversion Engine worker ──────────────────────────────────────────────────

class ConversionEngine:

    async def run_forever(self) -> None:
        logger.info("Conversion engine started")
        while True:
            try:
                redis = await get_redis()
                if not await is_agent_enabled(redis, "conversion"):
                    await asyncio.sleep(30)
                    continue

                # Process incoming conversion tasks from queue
                from app.core.redis import dequeue
                task = await dequeue(redis, QueueName.CONVERSION_TASKS, timeout=5)
                if task:
                    await self._dispatch(task)

                # Proactive scan every 15 minutes
                await self._scan_stalled_leads()
                await asyncio.sleep(900)   # 15 min

            except asyncio.CancelledError:
                break
            except Exception as e:
                logger.error(f"Conversion engine error: {e}")
                await asyncio.sleep(30)

    async def _dispatch(self, task: dict[str, Any]) -> None:
        task_type = task.get("type")
        try:
            if task_type == "pool_created":
                await self._handle_pool_created(task)
            elif task_type == "send_nudge":
                await self._send_nudge(task)
            elif task_type == "check_inactivity":
                await self._check_inactivity(task)
        except Exception as e:
            logger.error(f"Conversion task error [{task_type}]: {e}")

    # ── Pool created ──────────────────────────────────────────────────────────

    async def _handle_pool_created(self, task: dict[str, Any]) -> None:
        lead_id = uuid.UUID(task["lead_id"])
        async with AsyncSessionLocal() as db:
            lead = await get_lead(db, lead_id)
            if not lead:
                return

            if lead.stage != LeadStage.CONVERTED:
                await transition_stage(db, lead, LeadStage.CONVERTED, "pool created confirmed")

            await log_event(db, lead_id, EventType.POOL_CREATED, {
                "converted_at": datetime.now(timezone.utc).isoformat(),
                "onboarding_steps_completed": lead.onboarding_step,
            })

            # Increment daily metrics
            await self._increment_metric(db, "leads_converted")
            await db.commit()

            # Broadcast to dashboard via WebSocket
            await self._broadcast_conversion(str(lead_id), lead.project_name)
            logger.info(f"CONVERSION: {lead.project_name} created a pool!")

    # ── Proactive stall scanner ───────────────────────────────────────────────

    async def _scan_stalled_leads(self) -> None:
        """Find onboarding leads that have gone inactive and queue nudges."""
        now = datetime.now(timezone.utc)
        cutoff_inactivity = now - timedelta(hours=INACTIVITY_NUDGE_HOURS)
        cutoff_step       = now - timedelta(hours=MAX_HOURS_PER_STEP)

        async with AsyncSessionLocal() as db:
            from app.models.lead import Lead
            result = await db.execute(
                select(Lead).where(
                    Lead.stage == LeadStage.ONBOARDING,
                    Lead.is_deleted == False,
                    Lead.last_activity_at <= cutoff_inactivity,
                )
            )
            stalled = result.scalars().all()

        for lead in stalled:
            hours_inactive = (now - lead.last_activity_at.replace(tzinfo=timezone.utc)).total_seconds() / 3600

            # Determine nudge type
            if hours_inactive > STALE_ONBOARDING_DAYS * 24:
                nudge_type = "final_push"
            elif hours_inactive > MAX_HOURS_PER_STEP:
                nudge_type = "stuck_step"
            elif hours_inactive > INACTIVITY_NUDGE_HOURS:
                nudge_type = "inactivity"
            else:
                continue

            redis = await get_redis()
            await enqueue(redis, QueueName.CONVERSION_TASKS, {
                "type":           "send_nudge",
                "lead_id":        str(lead.id),
                "nudge_type":     nudge_type,
                "hours_inactive": hours_inactive,
            })

        if stalled:
            logger.info(f"Conversion scan: {len(stalled)} stalled leads queued for nudges")

    # ── Send nudge ────────────────────────────────────────────────────────────

    async def _send_nudge(self, task: dict[str, Any]) -> None:
        lead_id        = uuid.UUID(task["lead_id"])
        nudge_type     = task.get("nudge_type", "inactivity")
        hours_inactive = float(task.get("hours_inactive", 24))

        async with AsyncSessionLocal() as db:
            lead = await get_lead(db, lead_id)
            if not lead or lead.stage != LeadStage.ONBOARDING:
                return

            from app.agents.onboarding import ONBOARDING_STEPS
            step_idx  = min(lead.onboarding_step or 0, len(ONBOARDING_STEPS) - 1)
            step_name = ONBOARDING_STEPS[step_idx]["name"]

            lead_data = {
                "project_name":    lead.project_name,
                "chain":           lead.chain,
                "market_cap_usd":  lead.market_cap_usd,
                "score":           lead.score,
                "pain_signals":    lead.pain_signals,
                "onboarding_step": lead.onboarding_step,
            }

            message = await generate_nudge(
                lead=lead_data,
                nudge_type=nudge_type,
                step_name=step_name,
                hours_inactive=hours_inactive,
            )

            # Determine channel from active conversation
            channel = self._pick_channel(lead)
            if not channel:
                return

            # Enqueue as outreach task so it goes through the right platform sender
            active_conv = await self._get_active_conv(db, lead_id)
            if active_conv:
                await enqueue(await get_redis(), QueueName.OUTREACH_TASKS, {
                    "type":             "reply",
                    "lead_id":          str(lead_id),
                    "conversation_id":  str(active_conv.id),
                    "channel":          channel.value,
                    "inbound_message":  "[system nudge]",
                    "override_content": message,
                })

            await log_event(db, lead_id, EventType.NUDGE_SENT, {
                "nudge_type":     nudge_type,
                "hours_inactive": hours_inactive,
                "step_name":      step_name,
            })
            await db.commit()
            logger.info(f"Nudge [{nudge_type}] queued for {lead.project_name}")

    async def _check_inactivity(self, task: dict[str, Any]) -> None:
        """Scheduled inactivity check for a specific lead."""
        await self._send_nudge({**task, "nudge_type": "inactivity"})

    # ── Helpers ───────────────────────────────────────────────────────────────

    @staticmethod
    def _pick_channel(lead) -> OutreachChannel | None:
        links = lead.contact_links or {}
        for ch in (OutreachChannel.TELEGRAM, OutreachChannel.TWITTER, OutreachChannel.DISCORD):
            if ch.value in links:
                return ch
        return None

    @staticmethod
    async def _get_active_conv(db, lead_id: uuid.UUID):
        from app.models.lead import Conversation
        result = await db.execute(
            select(Conversation).where(
                Conversation.lead_id == lead_id,
                Conversation.is_active == True,
            ).order_by(Conversation.created_at.desc()).limit(1)
        )
        return result.scalar_one_or_none()

    @staticmethod
    async def _increment_metric(db, field: str) -> None:
        from app.models.lead import DailyMetrics
        today = datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0)
        result = await db.execute(
            select(DailyMetrics).where(DailyMetrics.date == today)
        )
        row = result.scalar_one_or_none()
        if row:
            setattr(row, field, getattr(row, field, 0) + 1)
        else:
            row = DailyMetrics(date=today, **{field: 1})
            db.add(row)

    @staticmethod
    async def _broadcast_conversion(lead_id: str, project_name: str) -> None:
        try:
            from app.services import ws_registry
            await ws_registry.broadcast({
                "event":        "conversion",
                "lead_id":      lead_id,
                "project_name": project_name,
                "timestamp":    datetime.now(timezone.utc).isoformat(),
            })
        except Exception as e:
            logger.debug(f"WS broadcast failed: {e}")


# ── Urgency scheduler — fires once per day ─────────────────────────────────────

async def schedule_daily_urgency_sweep(redis) -> None:
    """
    Schedule an urgency nudge sweep for all hot leads that haven't converted in 3+ days.
    Called once on startup and then every 24h.
    """
    run_at = datetime.now(timezone.utc) + timedelta(hours=24)
    await schedule_task(redis, ScheduleKey.NUDGES, {
        "type": "urgency_sweep",
    }, run_at=run_at)
